[package]
name = "taipo"
version = "0.1.0"
authors = ["Michael Millwood <imanotgate@gmail.com>"]
edition = "2018"

[dependencies]
glob = "0.3.0"
rayon = "1.3.0"
libc = "0.2"
rusqlite = { version = "*", features = ["bundled"] }
sdl2 = "0.33.0"

[build-dependencies]
bindgen = "0.53.2"