[package]
name = "taipo"
version = "0.1.0"
authors = ["Michael Millwood <imanotgate@gmail.com>"]
edition = "2018"

[dependencies]
glob = "0.3.0"
rayon = "1.3.0"
libc = "0.2"
diesel = { version = "1.4.4", features = ["sqlite"] }
sdl2 = "0.33.0"
# nalgebra = {version = "0.21.0", features = ["mint"] }
# serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
bindgen = "0.53.2"